### ISSUE TITLE
Fix the search suggestions not working on the trophy page

### ISSUE THREAD

**Issue by code-arman** [shstrophies/SHSTrophies#31]
On every other page, the suggestions work except for on the trophy page. On the trophy page, if you type in jeff for example, all of the suggestions disappear. This search bar should work like the rest of the search bars

![IMG_1520](https://user-images.githubusercontent.com/46976119/83103666-ff191480-a06b-11ea-9d34-1392bf41f5bb.JPG)

**Comment by kujjwal** [comment]
Also, pressing the back button there leaves the search suggestions page down
